[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = [
    "wasm32-unknown-unknown",
    # Windows
    "x86_64-pc-windows-gnu",
    "aarch64-pc-windows-msvc",
    # Linux
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    # macOS
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
]
